version: '3.8'

services:
  airobotics-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airobotics_client
    environment:
      - ROS_DOMAIN_ID=0
      - ENV_METASEJONG_TEAM_NAME=team_passion_for_challenges
      - ENV_METASEJONG_TEAM_TOKEN=87cef2059293b764451516c5e632e8b5
      - ENV_METASEJONG_TEAM_TARGET_STAGE=2
      - ENV_METASEJONG_SCENARIO_CAND=demo, dongcheon, jipyhyeon, gwanggaeto 
      - ENV_METASEJONG_SCENARIO=demo
      - VIRTUAL_ENV=/venv/metacom_client_env
      - PATH=/venv/metacom_client_env/bin:${PATH}
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTHORITY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY}:${XAUTHORITY}:ro
      - ./metasejong_competitor_ws:/workspace
      - ./demo/:/data/:ro
    network_mode: host
    privileged: true
    command: >
      bash -c "
      cd /workspace && 
      source /opt/ros/humble/setup.bash && 
      rm -rf build install log && 
      colcon build --packages-select airobotics_app --symlink-install && 
      source /workspace/install/setup.bash && 
      unset ROS_PACKAGE_PATH && 
      ros2 run airobotics_app airobotics_node"